### ISSUE TITLE
Keep the cursor at its current position

### ISSUE THREAD

**Issue by lekhnath** [vmsynkov/colonize#3]
It would be nice to have a feature of retaining current cursor position after inserting semicolon at EOL.

**Comment by caiolopes** [comment]
@lekhnath I just added this feature and made a PR. Let's see what @vmsynkov will think about it and probably soon it will be in the vscode marketplace.

**Comment by lekhnath** [comment]
@caiolopes sounds great.

**Comment by vmsynkov-zz** [comment]
It is possible now with the ctrl+alt+enter shortcut. At first i used ctrl+enter and even published a newer version, but than i realized that i forgot to check the default vsc shortcuts and found ctrl+enter to be "add new line below", so i chose to add alt as some people might be used to that.
