### ISSUE TITLE
Change key bindings

### ISSUE THREAD

**Issue by GrahamLab** [vmsynkov/colonize#6]
Hi 
Is it possible to change the key bindings?

**Comment by TedYav** [comment]
@GrahamLab You can, just do command + shift + p and type "Open Keyboard Shortcuts File"
In the `keybindings.json` file you can set whatever hotkeys you want. I had to do this as I think there's a conflict with another extension I've added. For example, I put:

```
{
    "key": "shift+cmd+enter",
    "command": "colonize.newline",
    "when": "editorTextFocus"
  },
  {
    "key": "alt+enter",
    "command": "colonize.hold",
    "when": "editorTextFocus"
  }
```

colonize gives you three commands, that you can view by clicking on the colonize extension in the marketplace, and clicking the Contributions tab.
